const times = [{ value: 2, label: '2 hours', note: 'A little local detour' }, { value: 4, label: '4 hours', note: 'A slow half-day' }, { value: 5, label: 'Half-day', note: 'Room to get lost' }, { value: 8, label: 'Full-day', note: 'Make a day of it' }];
const budgets = [{ value: 500, label: 'Rs. 500', note: 'Keep it easy' }, { value: 1000, label: 'Rs. 1,000', note: 'A few extra treats' }, { value: 2000, label: 'Rs. 2,000', note: 'Follow your curiosity' }, { value: 'unlimited', label: 'No limit', note: 'See where the day goes' }];
const interests = [{ value: 'food', label: 'Food', emoji: '🥟' }, { value: 'history', label: 'History', emoji: '🏛️' }, { value: 'culture', label: 'Culture', emoji: '🎭' }, { value: 'nature', label: 'Nature', emoji: '🌿' }, { value: 'photography', label: 'Photography', emoji: '📷' }, { value: 'shops', label: 'Shops', emoji: '🧺' }, { value: 'experiences', label: 'Experiences', emoji: '🪔' }, { value: 'art', label: 'Art', emoji: '🎨' }];
export default function ExperienceForm({ value, onChange, onSubmit, loading, error }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  const toggle = (interest) => set('interests', value.interests.includes(interest) ? value.interests.filter((item) => item !== interest) : [...value.interests, interest]);
  const step = !value.hours ? 1 : !value.budget ? 2 : 3;
  return <div className="experience-form">
    <div className={`form-step ${step >= 1 ? 'step-active' : ''}`}><div className="step-heading"><span className="step-index">01</span><div><h2>How much time have you got?</h2><p>We'll find a route that fits your day.</p></div>{value.hours && <span className="step-done">✓</span>}</div><div className="option-grid time-options">{times.map((item) => <button type="button" key={item.value} className={`option-card ${Number(value.hours) === item.value ? 'selected' : ''}`} onClick={() => set('hours', item.value)}><span className="option-check">✓</span><b>{item.label}</b><small>{item.note}</small></button>)}</div></div>
    <div className={`form-step ${step >= 2 ? 'step-active' : 'step-locked'}`}><div className="step-heading"><span className="step-index">02</span><div><h2>What's your kind of budget?</h2><p>Small pleasures count, too.</p></div>{value.budget !== '' && <span className="step-done">✓</span>}</div>{step >= 2 && <div className="option-grid budget-options">{budgets.map((item) => <button type="button" key={item.value} className={`option-card ${String(value.budget) === String(item.value) ? 'selected' : ''}`} onClick={() => set('budget', item.value)}><span className="option-check">✓</span><b>{item.label}</b><small>{item.note}</small></button>)}</div>}</div>
    <div className={`form-step ${step >= 3 ? 'step-active' : 'step-locked'}`}><div className="step-heading"><span className="step-index">03</span><div><h2>What are you in the mood for?</h2><p>Pick as many as you like.</p></div></div>{step >= 3 && <><div className="interest-grid">{interests.map((item) => <label key={item.value} className={`interest-chip ${value.interests.includes(item.value) ? 'selected' : ''}`}><input type="checkbox" checked={value.interests.includes(item.value)} onChange={() => toggle(item.value)} /><span>{item.emoji}</span>{item.label}</label>)}</div><button type="button" className="button button-primary generate-button" onClick={onSubmit} disabled={loading}>{loading ? <><span className="button-spinner" /> Finding your route…</> : <>Generate My Adventure <span>↗</span></>}</button>{error && <p className="form-error" role="alert">{error}</p>}</>}</div>
    <div className="form-footnote"><span>✦</span> Thoughtfully matched to your time, budget, and interests.</div>
  </div>;
}
